### ISSUE TITLE
Can I use relative paths on Windows ?

### ISSUE THREAD

**Issue by Fred-Vatin** [rszyma/kanata-tray#47]
Hi,

I put `kanata-tray.exe` and `kanata-tray.toml` in the same directory as my kanata binaries.

![screen](https://github.com/user-attachments/assets/82f82ec7-c4ff-4725-ae05-659e5aa10298)

In my config, can I strip `D:\Programmes\Outils\Kanata\` ? If not, it would be awesome to add this feature.

## Tray config

```toml
'$schema' = 'https://raw.githubusercontent.com/rszyma/kanata-tray/main/doc/config_schema.json'
# See https://github.com/rszyma/kanata-tray for help with configuration.

[general]
allow_concurrent_presets = false

[presets.'default winIOv2']
autorun = true
#kanata_config = 'D:\Programmes\Outils\Kanata\kanata.kbd'
#kanata_executable = ''
# layer_icons = {  }
# tcp_port = 1234
# extra_args = ['-n', '-c=~/.config/kanata/another.kbd']

[presets.'wintercept']
#kanata_config = 'D:\Programmes\Outils\Kanata\kanata.kbd'
kanata_executable = 'D:\Programmes\Outils\Kanata\kanata_wintercept_cmd_allowed.exe'

[presets.'normal']
#kanata_config = 'D:\Programmes\Outils\Kanata\kanata.kbd'
kanata_executable = 'D:\Programmes\Outils\Kanata\kanata_cmd_allowed.exe'

[presets.'test']
kanata_config = 'D:\Programmes\Outils\Kanata\test.kbd'

[defaults]
kanata_executable = 'D:\Programmes\Outils\Kanata\kanata_winIOv2_cmd_allowed.exe' # if empty or omitted, system $PATH will be searched.
kanata_config = 'D:\Programmes\Outils\Kanata\kanata.kbd' # if empty or not omitted, kanata default config locations will be used.
#tcp_port = 5833 # if not specified, defaults to 5829

[defaults.layer_icons]
Base = 'Base.ico'
NavNum = 'NavNum.ico'
SWITCH = 'SWITCH.ico'
Edit = 'Edit.ico'
lock = 'lock.ico'
symbols = 'symbols.ico'
transparent = 'transparent.ico'
```
